updating project

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -329,7 +329,7 @@ jobs:
       - attach_workspace:
          at: ~/ 
       - restore_cache:
-          keys: [backend-dependencies]
+          keys: [backend-build]
 
       - run:
           name: Install dependencies
@@ -395,9 +395,9 @@ jobs:
               export FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
               if curl -s $FRONTEND_WEBSITE | grep "Welcome"
               then
-                exit 1
+                exit 0
               else
-                exit 2
+                exit 1
               fi 
       - destroy-environment
       - revert-migrations
@@ -495,9 +495,9 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [deploy-backend, deploy-frontend]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cloudfront-update:
+      #     requires: [deploy-backend, deploy-frontend]  #In fact it requires smoke-test
+      # - cleanup:
+      #     requires: [cloudfront-update]
 
 # VS Code Extension Version: 1.5.1
